/* Task 1.1. Add your movie data here
   and export it so it's available in server.js */

const movies = {
  tt0317219: {
    imdbID: "tt0317219",
    Title: "Cars",
    Released: "2006-06-09",
    Runtime: 116,
    Genres: ["Animation", "Adventure", "Comedy"],
    Directors: ["John Lasseter", "Joe Ranft"],
    Writers: ["Dan Fogelman", "John Lasseter", "Joe Ranft"],
    Actors: ["Owen Wilson", "Bonnie Hunt", "Paul Newman"],
    Plot: "On the way to the biggest race of his life, a hotshot rookie race car gets stranded in a rundown town and learns that winning isn't everything in life.",
    Poster: "https://m.media-amazon.com/images/M/MV5BMTg5NzY0MzA2MV5BMl5BanBnXkFtZTYwNDc3NTc2._V1_SX300.jpg",
    Metascore: 73,
    imdbRating: 7.3,
  },
  tt0448115: {
    imdbID: "tt0448115",
    Title: "Shazam!",
    Released: "2019-04-05",
    Runtime: 132,
    Genres: ["Action", "Adventure", "Comedy"],
    Directors: ["David F. Sandberg"],
    Writers: ["Henry Gayden", "Darren Lemke", "Bill Parker"],
    Actors: ["Zachary Levi", "Mark Strong", "Asher Angel"],
    Plot: "A newly fostered young boy in search of his mother instead finds unexpected super powers and soon gains a powerful enemy.",
    Poster: "https://m.media-amazon.com/images/M/MV5BZWM1YjdmOGQtNGYyMC00NjMwLTk1OWUtMGYzM2NjYjliYzYyXkEyXkFqcGc@._V1_SX300.jpg",
    Metascore: 71,
    imdbRating: 7.0,
  },
  tt2975590: {
    imdbID: "tt2975590",
    Title: "Batman v Superman: Dawn of Justice",
    Released: "2016-03-25",
    Runtime: 151,
    Genres: ["Action", "Adventure", "Sci-Fi"],
    Directors: ["Zack Snyder"],
    Writers: ["Bob Kane", "Bill Finger", "Jerry Siegel"],
    Actors: ["Ben Affleck", "Henry Cavill", "Amy Adams"],
    Plot: "Batman is manipulated by Lex Luthor to fear Superman. Superman's existence is meanwhile dividing the world and he is framed for murder during an international crisis.",
    Poster: "https://m.media-amazon.com/images/M/MV5BZTJkYjdmYjYtOGMyNC00ZGU1LThkY2ItYTc1OTVlMmE2YWY1XkEyXkFqcGc@._V1_SX300.jpg",
    Metascore: 44,
    imdbRating: 6.4,
  },
  tt0468569: {
    imdbID: "tt0468569",
    Title: "The Dark Knight",
    Released: "2008-07-18",
    Runtime: 152,
    Genres: ["Action", "Crime", "Drama"],
    Directors: ["Christopher Nolan"],
    Writers: ["Jonathan Nolan", "Christopher Nolan", "David S. Goyer"],
    Actors: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    Plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    Poster: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    Metascore: 84,
    imdbRating: 9.0,
  },
  tt4154796: {
    imdbID: "tt4154796",
    Title: "Avengers: Endgame",
    Released: "2019-04-26",
    Runtime: 181,
    Genres: ["Action", "Adventure", "Sci-Fi"],
    Directors: ["Anthony Russo", "Joe Russo"],
    Writers: ["Christopher Markus", "Stephen McFeely", "Stan Lee"],
    Actors: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"],
    Plot: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    Poster: "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg",
    Metascore: 78,
    imdbRating: 8.4,
  },
  tt0137523: {
    imdbID: "tt0137523",
    Title: "Fight Club",
    Released: "1999-10-15",
    Runtime: 139,
    Genres: ["Drama", "Thriller"],
    Directors: ["David Fincher"],
    Writers: ["Chuck Palahniuk", "Jim Uhls"],
    Actors: ["Brad Pitt", "Edward Norton", "Meat Loaf"],
    Plot: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    Poster: "https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_SX300.jpg",
    Metascore: 66,
    imdbRating: 8.8,
  },
  tt15398776: {
    imdbID: "tt15398776",
    Title: "Oppenheimer",
    Released: "2023-07-21",
    Runtime: 180,
    Genres: ["Biography", "Drama", "History"],
    Directors: ["Christopher Nolan"],
    Writers: ["Christopher Nolan", "Kai Bird", "Martin Sherwin"],
    Actors: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
    Plot: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    Poster: "https://m.media-amazon.com/images/M/MV5BN2JkMDc5MGQtZjg3YS00NmFiLWIyZmQtZTJmNTM5MjVmYTQ4XkEyXkFqcGc@._V1_SX300.jpg",
    Metascore: 88,
    imdbRating: 8.3,
  },
  tt0120737: {
    imdbID: "tt0120737",
    Title: "The Lord of the Rings: The Fellowship of the Ring",
    Released: "2001-12-19",
    Runtime: 178,
    Genres: ["Adventure", "Drama", "Fantasy"],
    Directors: ["Peter Jackson"],
    Writers: ["J.R.R. Tolkien", "Fran Walsh", "Philippa Boyens"],
    Actors: ["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
    Plot: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    Poster: "https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_SX300.jpg",
    Metascore: 92,
    imdbRating: 8.9,
  },
  tt0910970: {
    imdbID: "tt0910970",
    Title: "WALL·E",
    Released: "2008-06-27",
    Runtime: 98,
    Genres: ["Animation", "Adventure", "Family"],
    Directors: ["Andrew Stanton"],
    Writers: ["Andrew Stanton", "Pete Docter", "Jim Reardon"],
    Actors: ["Ben Burtt", "Elissa Knight", "Jeff Garlin"],
    Plot: "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
    Poster: "https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_SX300.jpg",
    Metascore: 95,
    imdbRating: 8.4,
  },
  tt1375666: {
    imdbID: "tt1375666",
    Title: "Inception",
    Released: "2010-07-16",
    Runtime: 148,
    Genres: ["Action", "Adventure", "Sci-Fi"],
    Directors: ["Christopher Nolan"],
    Writers: ["Christopher Nolan"],
    Actors: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    Plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    Poster: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
    Metascore: 74,
    imdbRating: 8.8,
  },
  tt0371746: {
    imdbID: "tt0371746",
    Title: "Iron Man",
    Released: "2008-05-02",
    Runtime: 126,
    Genres: ["Action", "Adventure", "Sci-Fi"],
    Directors: ["Jon Favreau"],
    Writers: ["Mark Fergus", "Hawk Ostby", "Art Marcum"],
    Actors: ["Robert Downey Jr.", "Gwyneth Paltrow", "Terrence Howard"],
    Plot: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
    Poster: "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg",
    Metascore: 79,
    imdbRating: 7.9,
  },
  tt0111161: {
    imdbID: "tt0111161",
    Title: "The Shawshank Redemption",
    Released: "1994-09-23",
    Runtime: 142,
    Genres: ["Drama"],
    Directors: ["Frank Darabont"],
    Writers: ["Stephen King", "Frank Darabont"],
    Actors: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    Plot: "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
    Poster: "https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_SX300.jpg",
    Metascore: 82,
    imdbRating: 9.3,
  },
};

module.exports = movies;
